### ISSUE TITLE
Hybrid velocity Jacobian MATLAB syntax

### ISSUE THREAD

**Issue by deep-learn** [nodonoughue/emitter-detection-book#1]
Is this a bug in the computation of the hybrid velocity jacobian? The syntax looks wrong. The inputs to `zeros` should be scalars.

https://github.com/nodonoughue/emitter-detection-book/blob/99fe3ea83ffc57a06869d43a7673fa72add5b85a/%2Bhybrid/jacobian.m#L81

Should it be this?

```matlab
Jv = cat(2,zeros(size(J_aoa)), zeros(size(J_tdoa)), J_fdoa_v);
```

Tough to test as-is since the examples scripts and `hybrid.computeCRLB` don't support the case with source having a non-zero velocity.

**Comment by nodonoughue** [comment]
Thanks for catching this. [It's been fixed](https://github.com/nodonoughue/emitter-detection-book/commit/558186588caf22de95a560a82f2482c91362dacb). I also rewrote it a bit to be more clear.

```
num_rows = size(J_fdoa_v,1);
num_zero_cols = size(J_aoa,2) + size(J_tdoa,2);
Jv = cat(2,zeros(num_rows, num_zero_cols), J_fdoa_v);
```
